services:
  # Server service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: inventory_manager_backend
    ports:
      - "3001:3000"
    env_file: stack.env
    environment:
      - MONGO_URI=mongodb://192.168.1.153:27017
      - LLM_URI=${LLM_URI}
      - PORT=${PORT}
      - GITHUB_OAUTH_CLIENT_ID=${GITHUB_OAUTH_CLIENT_ID}
      - GITHUB_OAUTH_CLIENT_SECRET=${GITHUB_OAUTH_CLIENT_SECRET}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_ACCESS_TOKEN_SECRET=${REFRESH_ACCESS_TOKEN_SECRET}
      - NODEMAILER_APP_PASSWORD=${NODEMAILER_APP_PASSWORD}


  # Client service
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: inventory_manager_frontend
    ports:
      - "204:80"
    env_file: stack.env
    environment:
      - VITE_APP_BACKEND_API = ${VITE_APP_BACKEND_API}
    depends_on:
      - server

  # Database service
