import "../styles/inventoryapp.css"
import {Link, Route, Routes, useParams} from "react-router-dom";
import Sidebar from "../components/Sidebar";
import MenuBtn from "../components/MenuBtn";
import Searchbar from "../components/Searchbar";
import { useEffect, useState } from "react";
import styled from "styled-components";
import useWindowDimensions from "../hooks/useWindowDimensions";
import { useSelector } from "react-redux";


const DisplayPanel = styled.div`
  width: 100%;
  height: 100%;
  display: grid;
  align-items: center;
  justify-content: center;
`

const Page = styled.div`
/* ----------------------------------------------
 * Generated by Animista on 2024-6-29 21:28:26
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation text-focus-in
 * ----------------------------------------
 */
@-webkit-keyframes text-focus-in {
  0% {
    -webkit-filter: blur(12px);
            filter: blur(12px);
    opacity: 0;
  }
  100% {
    -webkit-filter: blur(0px);
            filter: blur(0px);
    opacity: 1;
  }
}
@keyframes text-focus-in {
  0% {
    -webkit-filter: blur(12px);
            filter: blur(12px);
    opacity: 0;
  }
  100% {
    -webkit-filter: blur(0px);
            filter: blur(0px);
    opacity: 1;
  }
}

    animation: text-focus-in 1s cubic-bezier(0.550, 0.085, 0.680, 0.530) both;
    background-color: #e8e9f3;
    height: 100%;
    width: 100%;
    display: flex;
`


function InventoryApp() {

  const [sidebarToggle, setSidebarToggle] = useState(false);
  const [searchbarToggle, setSearchBarToggle] = useState(false);
  const {height, width} = useWindowDimensions();
  const {id} = useParams();

  const user = useSelector(state => state.auth);

  const sidebarHandler = () => {
    setSidebarToggle(!sidebarToggle);
  }

  const searchbarHandler = () => {
    setSearchBarToggle(!searchbarToggle);
    console.log("toggle called")
    return searchbarToggle;
  }

  const clickHandler = (e) => {
   
  }

  useEffect(()=>{
    if(width <= "768"){
      setSidebarToggle(true);
    }
    //console.log(user)
  },[width]);
  /**
   * <MenuBtn toggle = {sidebarHandler}></MenuBtn>
      <Sidebar id="sidebar" toggle = {sidebarToggle} searchbar_toggle = {searchbarHandler} max_width = "20%" clickHandler = {clickHandler}/>
      <div style = {{width: "100%", margin: "60px",}}>{data}</div>

 {(()=>{
          if(localStorage.getItem('isAuthenticated')){
            return (<div>welcome! {JSON.parse(localStorage.getItem('user')).FirstName}</div>)
          }else{
            return (<div>Not Authorized</div>)
          }
        })()}


 
   */
  return (
    
    <Page>
      <Searchbar toggle = {searchbarHandler} display = {searchbarToggle}></Searchbar>
      <MenuBtn toggle = {sidebarHandler}></MenuBtn>
      <Sidebar width = {width} id="sidebar" toggle = {sidebarToggle} searchbar_toggle = {searchbarHandler} max_width = "100%" clickHandler = {clickHandler}/>
      <DisplayPanel>
        {(()=>{
          if(user.isAuthenticated){
            return (<div>welcome! {user.user.FirstName || JSON.parse(localStorage.getItem('user')).FirstName} <br></br> Email: {JSON.parse(localStorage.getItem('user')).Email}</div>)
          }else{
            return (<div>Not Authorized</div>)
          }
        })()}
      </DisplayPanel>
      
      </Page>
  )
}

export default InventoryApp
