import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import styled from "styled-components"

const Variables = {
    pagecolor: "#e8e9f3",
    itemcardcolor: "",
}

const Page = styled.div`
    height: 100%;
    width: 100%;
    background-color: ${Variables.pagecolor};
    display: grid;
    align-items: center;
    justify-content: center;

`

const Cards = styled.div`
    background-color: ${Variables.itemcardcolor};
    width: 300px;
    height: 200px;
    border-radius: 5px;
    box-shadow: 0 0 10px grey;
`

const CardsInner = styled.div`
    margin: 10px;
    height: calc(100% - 20px);
    width: calc(100% - 20px);
    display: grid;
`

const Loading = styled.div`
/* ----------------------------------------------
 * Generated by Animista on 2024-8-8 19:36:51
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation jello-horizontal
 * ----------------------------------------
 */
@-webkit-keyframes jello-horizontal {
  0% {
    -webkit-transform: scale3d(1, 1, 1);
            transform: scale3d(1, 1, 1);
  }
  30% {
    -webkit-transform: scale3d(1.25, 0.75, 1);
            transform: scale3d(1.25, 0.75, 1);
  }
  40% {
    -webkit-transform: scale3d(0.75, 1.25, 1);
            transform: scale3d(0.75, 1.25, 1);
  }
  50% {
    -webkit-transform: scale3d(1.15, 0.85, 1);
            transform: scale3d(1.15, 0.85, 1);
  }
  65% {
    -webkit-transform: scale3d(0.95, 1.05, 1);
            transform: scale3d(0.95, 1.05, 1);
  }
  75% {
    -webkit-transform: scale3d(1.05, 0.95, 1);
            transform: scale3d(1.05, 0.95, 1);
  }
  100% {
    -webkit-transform: scale3d(1, 1, 1);
            transform: scale3d(1, 1, 1);
  }
}
@keyframes jello-horizontal {
  0% {
    -webkit-transform: scale3d(1, 1, 1);
            transform: scale3d(1, 1, 1);
  }
  30% {
    -webkit-transform: scale3d(1.25, 0.75, 1);
            transform: scale3d(1.25, 0.75, 1);
  }
  40% {
    -webkit-transform: scale3d(0.75, 1.25, 1);
            transform: scale3d(0.75, 1.25, 1);
  }
  50% {
    -webkit-transform: scale3d(1.15, 0.85, 1);
            transform: scale3d(1.15, 0.85, 1);
  }
  65% {
    -webkit-transform: scale3d(0.95, 1.05, 1);
            transform: scale3d(0.95, 1.05, 1);
  }
  75% {
    -webkit-transform: scale3d(1.05, 0.95, 1);
            transform: scale3d(1.05, 0.95, 1);
  }
  100% {
    -webkit-transform: scale3d(1, 1, 1);
            transform: scale3d(1, 1, 1);
  }
}
    height: fit-content;
    width: fit-content;
    background-color: grey;
    animation: jello-horizontal 1.2s linear infinite both;
    border-radius: 5px;
    padding: 10px;
`

function ItemCards({ItemName, ItemDescription, Username, ItemBarcode, ItemCategory, ItemID}){
    return (
        <Cards>
            <CardsInner>
                <div>{ItemName}</div>
                <div>{ItemDescription}</div>
                <div>{Username}</div>
                <div>{ItemBarcode}</div>
                <div>{ItemCategory}</div>
                <div>{ItemID}</div>
            </CardsInner>
        </Cards>
    )
}

export default function Products(){
    const [status, setStatus] = useState(false);
    const [items, setItems] = useState([]);
    const {user} = useParams();

    const fetchItem = async () => {
        const items = fetch("http://localhost:3000/api/item/read").then(res => res.json())
        console.log(await items)
        return items;
    }

    useEffect(()=> {
        fetchItem()
        .then((data) => {setItems(data); setStatus(true)});
        
    }, []);

    return (
        <Page>
            {status ? <ItemCards></ItemCards> : (<Loading>Loading...</Loading>)}
        </Page>
    )
}