import styled from "styled-components"
import { useEffect, useState } from "react";
import github from "../../assets/github-circle-svgrepo-com.svg"
import linkedin from "../../assets/linkedin-svgrepo-com.svg"
import portfolio from "../../assets/portfolio-case-business-suitcase-svgrepo-com.svg"
import { useDispatch } from "react-redux";
import { authSlice } from "../../features/authSlice";

const Page = styled.div`
/* ----------------------------------------------
 * Generated by Animista on 2024-7-1 18:2:47
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-top
 * ----------------------------------------
 */
@-webkit-keyframes slide-in-top {
  0% {
    -webkit-transform: translateY(-1000px);
            transform: translateY(-1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
    opacity: 1;
  }
}
@keyframes slide-in-top {
  0% {
    -webkit-transform: translateY(-1000px);
            transform: translateY(-1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
    opacity: 1;
  }
}


	-webkit-animation: slide-in-top 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
	animation: slide-in-top 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
  height: 100%;
  width: 100%;
  display: grid;

  grid-auto-flow: column;

`
const validEmail = new RegExp(
  '^[a-zA-Z0-9._:$!%-]+@[a-zA-Z0-9.-]+.[a-zA-Z]$'
);

const validName = new RegExp(
  "(^[A-Za-z]{3,16})([ ]{0,1})([A-Za-z]{3,16})?([ ]{0,1})?([A-Za-z]{3,16})?([ ]{0,1})?([A-Za-z]{3,16})"
);


const LeftWrapper = styled.div`
  display: grid;
  height: 100%;
  width: 100%;
`

const RightWrapper = styled.div`
  display: grid;
  border: 1px solid #babab6;
  margin: 70px;
  @media(max-width: 800px){
      margin: 0px;
      border: 0px;
  }
`

const Image = styled.img`
  height: 80%;
  width: auto;
  object-fit: contain;
  align-self: center;
  justify-self: center;
  border-radius: 2px;
  @media(max-width: 500px){
      width: 100%;
      height: auto;
  }
`

const RightWrapperInner = styled.div`
  width: 100%;
  height: 100%;
  display: grid;
  grid-template-areas:
  "header header"
  "bodyL bodyR"
  "bodyL bodyR"
  "bodyL bodyR"
  "bodyL bodyR";
  @media(max-width: 1140px){
      
      grid-template-areas:
      "header header"
      "bodyR bodyR"
      "bodyR bodyR"
      "bodyL bodyL"
      "bodyL bodyL";
  }
     
`

const Contact = styled.div`
  >* {
      display: grid;
      user-select: none;
      
      label{
          font-weight: bold;
      }
      input{
          height: 2rem;
          font-size: 1.5rem;
          background: none;
          border: none;
          outline: none;
          border-bottom: 1px solid black;
      }
      textarea{
          height: 10rem;
          background: none;
          outline: none;
          font-size: 1.5rem;
          resize: none;
          font-family: 'Martian Mono', monospace;
      }
  };
  button{
      height: 2rem;
      width: 7rem;
      background-color: #fcfbff;
      border: none;
      border-radius: 4px;
      font-size: 1.2em;
      display: grid;
      justify-content: center;
      font-family: 'Martian Mono', monospace;
      align-items: center;
      cursor: pointer;  
      justify-self: start;
      align-self: center;
      box-shadow: 0px 15px 35px -5px rgba(50, 88, 130, 0.32);
      transition: background-color 0.3s linear;
      &:hover{
          box-shadow: 0px 15px 35px -5px rgba(23, 53, 87, 0.59);
          background: #1f202a;
          color: white;
          text-shadow: 0px 0px 10px white;
      }

  }
  grid-area: bodyL;
  justify-self: center;
  align-self: center;
  display: grid;
  gap: 20px;
;
`

const ContactForm = () => {

  const [validE, setValidE] = useState(false);
  const [validN, setValidN] = useState(false);

  return (
      <Contact>
          <div>
              <label>Full Name:</label>
              <input style={{borderBottom: `1px solid ${validN ? 'black' : 'red'}`}} onChange = {(e) => setValidN(validName.test(e.target.value))}></input>
          </div>
          <div>
              <label >E-mail:</label>
              <input style = {{borderBottom: `1px solid ${validE ? 'black' : 'red'}`}} type="email" onChange = {(e) => setValidE(validEmail.test(e.target.value))}></input>
          </div>
          <div>
              <label>Message:</label>
              <textarea></textarea>
          </div>
          <div style = {{display: 'grid', alignItems: 'center', justifyContent: 'center'}}><button>Submit</button></div>
          
      </Contact> 
      
  )
}

const ContactInfo = styled.div`
  display: grid;
  grid-area: bodyR;
  width: 100%;
  height: 100%;
  align-items: center;
  justify-content: center;   
  >*{
      display: grid;
      
      t, e{
          
          font-size: 1.5rem;
          font-weight: bold;
      }

  }
  social{
      display: grid;
      grid-auto-flow: column;
      justify-content: space-evenly;
      align-items: center;

      img{
          user-select: none;
          height: 40px;
          width: 40px;
          border-radius: 10px;
          cursor: pointer;

          &:hover{
              box-shadow: 0px 15px 35px -5px rgba(23, 53, 87, 0.59);
              background: white;
              color: white;
              text-shadow: 0px 0px 10px white;
          }
      }
  }
  
`



export default function About(){

  const dispatch = useDispatch();
  useEffect(()=>{
    dispatch(authSlice.actions.checkToken());
  },[]);

    return (
        <Page>

            <RightWrapper>
                <RightWrapperInner>
                    <div style = {{gridArea: "header", fontSize: '3rem', fontWeight: 'bold', display: 'grid', alignSelf:'center', justifySelf: 'center', borderBottom: '1px solid  #babab6'}}>  Contact Me </div> 
                    <ContactForm></ContactForm>
                    <ContactInfo>
                        <div>
                            <t>Based in</t>
                            <address>New York</address>
                            <address>United States</address>
                        </div>
                        <div>
                            <e>Contact</e>
                            <e1>Chuan Chen</e1>
                            <e1>chuan.chen.info@gmail.com</e1>
                            <e1>(917)605-6373</e1>
                        </div>
                        <social >
                            <a href = "https://github.com/Chuan-Chen"><img src ={github} alt = "Github" draggable = "false"></img></a>
                            <a href = "https://www.linkedin.com/in/chuan-chen-496199214/"><img src = {linkedin} alt = "Linkedin" draggable = "false"></img></a>
                            <a href = "https://self.nauhc.dev/"><img src = {portfolio} alt = "Portfolio" draggable = "false"></img></a>
                        </social>
                        
                    </ContactInfo>
                </RightWrapperInner>
            </RightWrapper>
        </Page>
    )
}