import styled from "styled-components"
import { useSelector } from "react-redux";
import { useEffect, useState } from "react";
import { authSlice } from "../../features/authSlice";
import { useDispatch } from "react-redux";

const Page = styled.div`
/* ----------------------------------------------
 * Generated by Animista on 2024-7-1 18:2:47
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-top
 * ----------------------------------------
 */
@-webkit-keyframes slide-in-top {
  0% {
    -webkit-transform: translateY(-1000px);
            transform: translateY(-1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
    opacity: 1;
  }
}
@keyframes slide-in-top {
  0% {
    -webkit-transform: translateY(-1000px);
            transform: translateY(-1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
    opacity: 1;
  }
}


	-webkit-animation: slide-in-top 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
	animation: slide-in-top 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;

    height: 100%;
    width: 100%;

    display: grid;

`

const ProfileCard = styled.div`
  z-index: 2;
  position: absolute;
  align-self: center;
  justify-self: center;
  height: 70%;
  width: 50%;
  background-color: #f3f3ff;
  border-radius: 10px;
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
  display: grid;

`

const ProfilePicture = styled.div`
  border-radius: 100%;
  background-color: black;
  width: 200px;
  height: 200px;
  align-self: center;
  justify-self: center;
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);s
`

export default function Profile(){

    const user = useSelector(state => state.auth);
    const dispatch = useDispatch();
    useEffect(()=>{
      dispatch(authSlice.actions.checkToken());
    },[]);

    //<div>welcome! {user.user.FirstName || JSON.parse(localStorage.getItem('user')).FirstName} <br></br> Email: {JSON.parse(localStorage.getItem('user')).Email}</div>

    return (
        <Page>
            <div style = {{backgroundColor: "#b7b8c0", height: "40%", width: "100%"}}></div>
            
            <ProfileCard>
            <ProfilePicture></ProfilePicture>
            <div>
              <div>Name: {user.user.FirstName}</div>
              <div>Email: {JSON.parse(localStorage.getItem('user')).Email}</div>
            </div>
            </ProfileCard>
        </Page>
    )
}