import styled from "styled-components"
import { useSelector } from "react-redux";
import { useEffect, useState } from "react";
import { authSlice } from "../features/authSlice.js"
import { useDispatch } from "react-redux";
import FileUpload from "./FileUpload.jsx";

const Page = styled.div`

/* ----------------------------------------------
 * Generated by Animista on 2024-10-25 13:37:56
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation fade-in-fwd
 * ----------------------------------------
 */
@-webkit-keyframes fade-in-fwd {
  0% {
    -webkit-transform: translateZ(-80px);
            transform: translateZ(-80px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateZ(0);
            transform: translateZ(0);
    opacity: 1;
  }
}
@keyframes fade-in-fwd {
  0% {
    -webkit-transform: translateZ(-80px);
            transform: translateZ(-80px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateZ(0);
            transform: translateZ(0);
    opacity: 1;
  }
}
	-webkit-animation: fade-in-fwd 0.6s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
	        animation: fade-in-fwd 0.6s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
    width: 100vw;
    height: 100vh;
`

const CloseButton = styled.button`

`

const SaveButton = styled.button`

`

function saveFunc(){
    
}


export default function EditProfile({handleScreenToggle}){

    const user = useSelector(state => state.auth);
    const dispatch = useDispatch();



    const [imageURL, setimageURL] = useState({
      "status" : "pending",
      "url" : ""
    });

    const handleImage = (status, url) => {
        setimageURL({"status" : status, "url" : url})
      }

    return (
        <Page>

            <CloseButton onClick={handleScreenToggle}>Back</CloseButton>
            <FileUpload imageStatus = {imageURL.status} imageURL = {imageURL.url} handleImage={handleImage}>
            </FileUpload>
            <img alt = "Profile Picture" src = {user.user.ProfilePicture}></img>
            <div>{user.user.FirstName} {user.user.LastName}</div>
            <SaveButton onClick={()=>{
                    handleScreenToggle();
                    saveFunc();
                    }}>
                        Save
            </SaveButton>
        </Page>
    )
}